api_root_path: /
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
server_private_key: '**********'
server_public_key: HsKvfHsAFNGykFi/zMssay0xajoHvY30IcYPGDCXrGU=
service_name: encryption_key_store
vault_path: ekss
vault_role_id: '**********'
vault_secret_id: '**********'
vault_url: http://127.0.0.1:8200
vault_verify: true
workers: 1
