api_root_path: /
auto_reload: false
db_name: keystore
db_url: "mongodb://localhost:27017"
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
service_name: encryption_key_store
workers: 1
