[build-system]
requires = ["setuptools>=67.7.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ekss"
version = "1.0.1"
description = "Encryption Key Store Sevice - providing crypt4gh file secret extraction, storage and envelope generation"
readme = "README.md"
authors = [
    { name = "German Human Genome Phenome Archive (GHGA)", email = "contact@ghga.de" },
]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]
dependencies = [
    "ghga-service-commons[all]>=1.1.1",
    "hexkit>=1.0.0",
    "typer>=0.6.0",
    "crypt4gh>=1.6",
    "hvac>=2",
]

[project.license]
text = "Apache 2.0"

[project.urls]
Repository = "https://github.com/ghga-de/encryption-key-store-service"

[project.scripts]
ekss = "ekss.__main__:run"

[tool.setuptools.packages.find]
where = ["src"]
