# Please only mention the non-default settings here:

vault_host: "http://127.0.0.1"
vault_port: 8200
vault_token: "dummy-token"
server_private_key: "9iYLar4OyeBzKJY8xQ8BAiGUe49wmqRPtcj240+VmjQ="
server_public_key: "HsKvfHsAFNGykFi/zMssay0xajoHvY30IcYPGDCXrGU="
