# Please only mention the non-default settings here:

db_connection_str: "mongodb://localhost:27017"
db_name: "keystore"
server_private_key: "9iYLar4OyeBzKJY8xQ8BAiGUe49wmqRPtcj240+VmjQ="
server_public_key: "HsKvfHsAFNGykFi/zMssay0xajoHvY30IcYPGDCXrGU="
